### ISSUE TITLE
Compile Error "patterns aren't allowed in methods without bodies"

### ISSUE THREAD

**Issue by dekonstruktiv** [jmatraszek/microbrust#4]
on a reasonably clean ubuntu 17.10 installation i'm getting the following compile error, confirmed on 3 different but similar machines:

```
   Compiling pkg-config v0.3.8
   Compiling bitflags v0.2.1
   Compiling rustc-serialize v0.3.19
   Compiling semver v0.1.20
   Compiling winapi v0.2.8
   Compiling memalloc v0.1.0
   Compiling termbox-sys v0.2.9
   Compiling bitflags v0.3.3
   Compiling winapi-build v0.1.1
   Compiling num-traits v0.1.35
error[E0642]: patterns aren't allowed in methods without bodies
   --> /home/gtz/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-serialize-0.3.19/src/serialize.rs:147:45
    |
147 |                                             &f_name: &str,
    |                                             ^^^^^^^

   Compiling libc v0.2.15
   Compiling kernel32-sys v0.2.2
   Compiling rand v0.3.14
   Compiling rustc_version v0.1.7
   Compiling alsa-sys v0.0.8
   Compiling num-integer v0.1.32
error: failed to run custom build command for `alsa-sys v0.0.8`
process didn't exit successfully: `/home/gtz/Downloads/microbrust/microbrust/target/debug/build/alsa-sys-8585bd72a32905b6/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Failed to run `\"pkg-config\" \"--libs\" \"--cflags\" \"alsa\"`: No such file or directory (os error 2)"', src/libcore/result.rs:916:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...
error: aborting due to previous error

error: Could not compile `rustc-serialize`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by jmatraszek** [comment]
Thanks from opening an issue. This shouldn't be too hard to fix, expect a new release in a few days.

**Comment by dekonstruktiv** [comment]
On Tue, 2018-06-05 at 09:16 +0000, Jakub Matraszek wrote:
> Thanks from opening an issue. This shouldn't be too hard to fix,
> expect a new release in a few days.

maybe noteworthy: on ubuntu 18.04 i get the same compile error at a
different liocation:

   Compiling winapi-build v0.1.1
error[E0642]: patterns aren't allowed in methods without bodies
   --> /home/gtz/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-
serialize-0.3.19/src/serialize.rs:147:45
    |
147 |                                             &f_name: &str,
    |                                             ^^^^^^^

**Comment by thk** [comment]
Hi jmatraszek,

have you already already tried to work this issue? Unfortunately I need a fix - or at least a workaround - soon, since I want to use the Microbrute in a synced setup and I have no Win/Mac-System around. Please don't get me wrong, I don't want to pressure you into work but I would try to put my own hands on this bug if you say, you don't have time for this at the moment. Sadly I'd have to learn some Rust first. ;-)

Regards,
Thomas

btw: Thx for this very useful software! It made me buy this cool synth!

**Comment by jmatraszek** [comment]
Hi @thk,
I should be able to release the fix during the weekend.

**Comment by thk** [comment]
That'd be great! Thx for your reply...

**Comment by dekonstruktiv** [comment]
Incidentally, I noticed the arturia control center software works with playonlinux/wine in Ubuntu 17.whatever.

**Comment by jmatraszek** [comment]
HI @dekonstruktiv, @thk,
thanks for your bug reports. This is now fixed in `master` branch. Will also create a binary release today, so you do not have to compile the project itself. I didn't have much time to test this with Microbrute, just did a quick check, so if you find any bug please open a new issue.

Best,
J

**Comment by jmatraszek** [comment]
And you can find the precompiled binaries here: https://github.com/jmatraszek/microbrust/releases/tag/v1.2.0

**Comment by dekonstruktiv** [comment]
> This is not fixed in master branch.

i'm confused :-)
i suspect you meant "now fixed"?

anyway, thanks for your effort?

**Comment by jmatraszek** [comment]
Ah, yeah, just made a typo. This is fixed. :)

**Comment by thk** [comment]
Hi @jmatraszek,

I could test the fixed version (build from source) today with the microbrute connected: works perfectly! :-) Thx for your effort...

Best,
Thomas
